---
version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=weather-data
    volumes:
      - './influxdb:/var/lib/influxdb'

  weatherfetcher:
    build:
      context: ./Weatherfetcher
      dockerfile: Dockerfile
    container_name: weatherfetcher
    restart: unless-stopped
    network_mode: 'bridge'
    environment:
      - UPDATE_INTERVAL=300
    links:
      - influxdb
    depends_on:
      - influxdb
