---
version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=weather-data
    volumes:
      - './influxdb:/var/lib/influxdb'

  weatherfetcher:
    build:
      context: ./Weatherfetcher
      dockerfile: Dockerfile
    container_name: weatherfetcher
    restart: unless-stopped
    network_mode: 'bridge'
    environment:
      - POLLING_INTERVAL=${POLLING_INTERVAL}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - DISTANCE=${DISTANCE}
      - DB_CONNECTION=localhost:8086
    links:
      - influxdb
    depends_on:
      - influxdb
